version: 3

vars:
  GOLANGCI_LINT_VERSION: v1.60.1

tasks:

  lint:
    desc: "run golangci-lint"
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}} run ./...
  test:
    desc: "run tests"
    cmd: go test ./... --count=1

